Kaushal erp bugfix
pseudocode-skyai/erpnext pull request #2
Opened 2022-07-08 14:32 UTC by PITPL-Kaushal-Khute

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2022-07-11 14:12 UTC, PITPL-Akshay-Prajapati requested changes

2022-07-11 14:12 UTC, PITPL-Akshay-Prajapati commented on erpnext/selling/doctype/customer/customer.js
> +						function () {
don't added any code in this function. if unnecessary remove it.

2022-07-11 14:12 UTC, PITPL-Akshay-Prajapati commented on erpnext/selling/doctype/customer/customer.py
> +from pymysql import NULL
is not required remove it

2022-07-11 14:12 UTC, PITPL-Akshay-Prajapati commented on erpnext/selling/doctype/customer/customer.py
> +from traitlets import Undefined
is not required remove it

2022-07-11 14:14 UTC, PITPL-Akshay-Prajapati commented on erpnext/stock/doctype/batch/batch.js
> +
remove unnecessary blank lines.

2022-07-11 14:14 UTC, PITPL-Akshay-Prajapati approved these changes

2022-07-11 14:14 UTC, merged

2022-07-12 04:54 UTC, PITPL-Kaushal-Khute commented on erpnext/stock/doctype/batch/batch.js
> +
ok, i will change