Hide print opation in stock UOM field
pseudocode-skyai/erpnext pull request #26
Opened 2022-07-25 12:54 UTC by PITPL-Gayatri-Gajjjar

2022-07-26 10:20 UTC, PITPL-Akshay-Prajapati requested changes
tab spacing issues will create Conflict. make sure to push changes only related to your field not tabbing. A standard spacing(tabing space) should be 4.

2022-07-29 14:39 UTC, PITPL-Akshay-Prajapati requested changes

2022-07-29 14:39 UTC, PITPL-Akshay-Prajapati commented on erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
>  {
don't push indention change.

2022-07-29 14:39 UTC, PITPL-Akshay-Prajapati commented on erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
> + "actions": [],
don't push indention change.

2022-08-17 09:24 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
>  {
Done

2022-08-17 09:24 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
> + "actions": [],
Done

2022-10-10 07:17 UTC, closed without merging