Set warehouse Supplier - U  in  Purchase  Order.
pseudocode-skyai/erpnext pull request #28
Opened 2022-07-27 05:28 UTC by PITPL-Gayatri-Gajjjar

2022-07-29 14:16 UTC, PITPL-Akshay-Prajapati requested changes
need only single line change in warehouse field. this type of changes are dangerous for migration.

2022-07-29 14:26 UTC, PITPL-Akshay-Prajapati requested changes
remove indention change and push only required changes. this change harmful.

2022-07-29 14:40 UTC, PITPL-Akshay-Prajapati requested changes

2022-07-29 14:40 UTC, PITPL-Akshay-Prajapati commented on erpnext/buying/doctype/purchase_order/purchase_order.json
> + "actions": [],
don't push indention change.

2022-08-17 09:01 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/buying/doctype/purchase_order/purchase_order.json
> + "actions": [],
Done

2022-08-17 09:25 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/buying/doctype/purchase_order/purchase_order.json
> + "actions": [],
Done

2022-10-10 07:18 UTC, closed without merging