hide unnessary field PO and PR
pseudocode-skyai/erpnext pull request #31
Opened 2022-08-03 06:28 UTC by PITPL-Gayatri-Gajjjar

- hide unnecessary field in listview in purchase order
-Grand Total (Company Currency)  in listview in purchase receipt

2022-08-16 05:41 UTC, PITPL-Kaushal-Khute requested changes
remove indention change from json file.

2022-08-16 05:41 UTC, PITPL-Kaushal-Khute commented on erpnext/buying/doctype/purchase_order/purchase_order.json
> + "actions": [],
remove indention change from json file.

2022-08-16 05:41 UTC, PITPL-Kaushal-Khute commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.json
> + "actions": [],
remove indention change from json file.

2022-08-17 07:27 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.json
> + "actions": [],
Done

2022-08-17 07:27 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/buying/doctype/purchase_order/purchase_order.json
> + "actions": [],
Done

2022-08-17 09:25 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/buying/doctype/purchase_order/purchase_order.json
> + "actions": [],
Done

2022-10-10 07:19 UTC, closed without merging