Mandatory Batch No andExpiry Date and defulat todate set in Manufacturing Date.
pseudocode-skyai/erpnext pull request #33
Opened 2022-08-03 09:15 UTC by PITPL-Gayatri-Gajjjar

2022-08-16 05:40 UTC, PITPL-Kaushal-Khute requested changes
remove indention change from json file.

2022-08-16 05:40 UTC, PITPL-Kaushal-Khute commented on erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
> + "actions": [],
remove indention change from json file.

2022-08-16 05:40 UTC, PITPL-Kaushal-Khute requested changes
remove indention change from json file.

2022-08-17 09:25 UTC, PITPL-Gayatri-Gajjjar commented on erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
> + "actions": [],
Done

2022-10-10 07:26 UTC, closed without merging